name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Build no_std
      run: cargo build --no-default-features
    - name: Build no_std with allocator
      run: cargo build --no-default-features --features alloc
    - name: Test
      run: cargo test
    - name: Test no_std
      run: cargo test --no-default-features
    - name: Test no_std with allocator
      run: cargo test --no-default-features --features alloc